### ISSUE TITLE
No longer require $ponyDocsProductsList

### ISSUE THREAD

**Issue by ekristen** [splunk/ponydocs#2]
It would nice not to have to edit this array anymore for products. Thanks for all you do!

```
// NOTE: this *must* match what is in Documentation:Products.
// This will be fixed in later versions
$ponyDocsProductsList = array('Foo');
```

**Comment by firebus** [comment]
Currently PonyDocsExtension uses this variable to set up the -docteam and -preview groups. We could easily do this with Documentation:Products or the PonyDocsProduct class instead.
