### ISSUE TITLE
How to log to $SPLUNK_HOME/var/log/my_app.log?

### ISSUE THREAD

**Issue by kkirsche** [splunk/ponydocs#66]
Good morning, I wanted to check in and see if there is a way using the `logging.conf` file found in `$SPLUNK_HOME/etc/apps/MY_APP/default/logging.conf` to log to `$SPLUNK_HOME/var/log/my_app.log` instead of to `$SPLUNK_HOME/etc/apps/MY_APP/my_app.log` which seems to be the default behavior with the following log file:

```python
[loggers]
keys = root

[logger_root]
level = WARNING    ; Default: WARNING
handlers = file   ; Default: stderr
propagate = 0     ; Default: 1

[handlers]
keys=file

[handler_file]
class = logging.FileHandler
level = NOTSET
# (filename, mode='a', encoding=None, delay=False)
args = ('my_app.log', 'a', 'utf-8', True)
formatter = my_app

[formatters]
keys = my_app

[formatter_my_app]
format=%(levelname)s:%(module)s: %(message)s
```

I've read through the python documentation but I haven't had much luck. Would you be able to help with understanding Splunk's logging?

**Comment by firebus** [comment]
Hi there! This isn't the best place for general Splunk questions - you should try http://answers.splunk.com or #splunk on efnet.
